=== Wan-de-Rock/TIN/assignments/12/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="name" type="xs:token" />
    <xs:element name="tagline" type="xs:string" />
    <xs:element name="date" type="xs:date" />
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="guestsnumber">
        <xs:simpleType>
            <xs:union>
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0" />
                        <xs:maxInclusive value="120" />
                    </xs:restriction>
                </xs:simpleType>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="full" />
                        <xs:enumeration value="empty" />
                    </xs:restriction>
                </xs:simpleType>

            </xs:union>
        </xs:simpleType>
    </xs:element>

    <xs:element name="event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
                <xs:element ref="tagline" />
                <xs:element ref="date" />
                <xs:element ref="email" />
                <xs:element ref="guestsnumber" />
            </xs:sequence>
            <xs:attribute name="eventid" type="xs:positiveInteger" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:element name="action">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="event" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueEventId">
            <xs:selector xpath="event" />
            <xs:field xpath="@eventid" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== Wan-de-Rock/TIN/assignments/12/event.xml
<?xml version="1.0" encoding="UTF-8"?>

<action
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="event.xsd"> 

    <event eventid="1"> <!-- unique -->
        <name>Coachella</name>
        <tagline>Welcome to Coachella.</tagline>
        <date>2023-04-14</date> <!-- date -->
        <email>coachella@mail.com</email> <!-- RegEx -->
        <guestsnumber>full</guestsnumber> <!-- union & restriction -->
    </event>
    <event eventid="2">
        <name>Electric Forest</name>
        <tagline>Happy New Year</tagline>
        <date>2023-07-22</date>
        <email>some@mail.com</email>
        <guestsnumber>100</guestsnumber>
    </event>
    <event eventid="3">
        <name>Rock in Rio</name>
        <tagline>Voltei. (I'm back).</tagline>
        <date>1985-01-11</date>
        <email>rockInRio@mail.com</email>
        <guestsnumber>120</guestsnumber>
    </event>
    <event eventid="4">
        <name>Lollapalooza</name>
        <tagline>Good music</tagline>
        <date>2023-08-03</date>
        <email>lollapalooza@mail.com</email>
        <guestsnumber>empty</guestsnumber>
    </event>
    <event eventid="5">
        <name>Tomorrowland</name>
        <tagline>One world, one heart.</tagline>
        <date>2023-07-15</date>
        <email>tomorrowland@mail.com</email>
        <guestsnumber>full</guestsnumber>
    </event>

</action>
